#!/bin/bash
# Clones BtbN/FFmpeg-Builds at a pinned commit and trims it to the dependencies this build needs.
#   ./prepare.sh <workdir>
#
# BtbN's generate.sh starts from the LAST script in scripts.d (zz-final.sh) and only builds the stages it reaches
# through each script's ffbuild_depends. download.sh, however, fetches the sources of EVERY script that exists.
# So this script (1) computes the transitive dependency closure of ROOTS from the scripts' ffbuild_depends,
# (2) deletes every stage outside it, and (3) rewrites zz-final.sh so its dependencies are exactly ROOTS.
set -euo pipefail

BTBN_REPO="https://github.com/BtbN/FFmpeg-Builds.git"
# Reviewed 2026-09-15; bump deliberately (BtbN renames stages and changes toolchains).
BTBN_COMMIT="${BTBN_COMMIT:-3e6685eda92f9288c15ac320139622dcedca09a4}"

# Flavour selects the add-in that will be applied and the dependency stages kept for it.
#   trimmed     (default) GPL video build for Video Converter    -> ./build.sh <t> gpl-shared  9.0 trimmed
#   audio-lgpl  LGPL v2.1 audio-only build for Audio Converter   -> ./build.sh <t> lgpl-shared 9.0 audio-lgpl
# Stage names are the part after the numeric prefix (50-x264.sh -> x264, 45-fonts/ -> fonts).
# Per-target gating (libvpx and onevpl are win64-only, ffnvcodec needs FFmpeg > 8.1 on ARM64) is done by the
# scripts' own ffbuild_enabled, so listing them here is harmless on winarm64.
FLAVOR="${FLAVOR:-trimmed}"
case "$FLAVOR" in
    trimmed)
        ROOTS=(
            x264 x265 svtav1 dav1d libvpx libopus libmp3lame   # codecs
            libass                                             # subtitle burn-in (pulls fonts, fribidi, libunibreak, libxml2)
            zimg zlib libiconv                                 # zscale, compressed MKV/PNG, charset conversion
            ffnvcodec amf onevpl                               # NVENC, AMF, QSV headers/dispatchers
        ) ;;
    audio-lgpl)
        # libvorbis pulls libogg; libmp3lame pulls libiconv (its ffbuild_depends), which adds --enable-iconv.
        # zlib: png cover art and compressed Matroska tracks. Nothing GPL, nothing needing --enable-version3.
        ROOTS=( libmp3lame libopus libvorbis zlib libiconv ) ;;
    *)
        echo "prepare.sh: unknown FLAVOR '$FLAVOR' (trimmed | audio-lgpl)" >&2; exit 1 ;;
esac

HERE="$(cd "$(dirname "$0")" && pwd)"
WORK="${1:-$HERE/.work}"

rm -rf "$WORK"
git clone "$BTBN_REPO" "$WORK"
git -C "$WORK" checkout "$BTBN_COMMIT"
cd "$WORK"

# Resolve a stage name to its path (a script or a directory of scripts).
stage_path() {
    local m=(scripts.d/??-"$1" scripts.d/??-"$1".sh)
    for p in "${m[@]}"; do [[ -e "$p" ]] && { echo "$p"; return; }; done
    echo "prepare.sh: no stage named '$1'" >&2
    return 1
}

# Print the ffbuild_depends names declared by a script (textual parse; the scripts only `echo` names there).
stage_deps() {
    local scripts=()
    if [[ -d "$1" ]]; then scripts=("$1"/*.sh); else scripts=("$1"); fi
    sed -n '/^ffbuild_depends()/,/^}/p' "${scripts[@]}" | grep -oE 'echo +[A-Za-z0-9_.-]+' | awk '{print $2}'
}

declare -A KEEP
queue=("${ROOTS[@]}")
while ((${#queue[@]})); do
    name="${queue[0]}"; queue=("${queue[@]:1}")
    [[ -v KEEP["$name"] ]] && continue
    KEEP["$name"]="$(stage_path "$name")"
    while IFS= read -r dep; do [[ -n "$dep" ]] && queue+=("$dep"); done < <(stage_deps "${KEEP[$name]}")
done

echo "== stages kept ($((${#KEEP[@]}))): $(printf '%s ' "${!KEEP[@]}" | tr ' ' '\n' | sort | tr '\n' ' ')"
for entry in scripts.d/*; do
    [[ "$(basename "$entry")" == zz-final.sh ]] && continue
    keep=0
    for p in "${KEEP[@]}"; do [[ "$p" == "$entry" ]] && keep=1; done
    if ((keep == 0)); then rm -rf "$entry"; fi
done
echo "== stages dropped: $(git status --porcelain scripts.d | wc -l) entries"

# Entry stage: generate.sh walks from the last script in scripts.d, so this decides what gets built.
{
    echo '#!/bin/bash'
    echo '# Generated by ffmpeg-builds/prepare.sh: the dependency roots of the trimmed build.'
    echo 'SCRIPT_SKIP="1"'
    echo 'ffbuild_depends() {'
    printf '    echo %s\n' "${ROOTS[@]}"
    echo '}'
    for fn in ffbuild_enabled ffbuild_dockerfinal ffbuild_dockerdl ffbuild_dockerlayer ffbuild_dockerstage ffbuild_dockerbuild ffbuild_ldexeflags; do
        echo "$fn() { return 0; }"
    done
} > scripts.d/zz-final.sh

# Let CI reuse BtbN's public base images (ghcr.io/btbn/ffmpeg-builds/base-<target>) instead of rebuilding the
# cross toolchain: set BTBN_IMAGE_REPO=btbn/ffmpeg-builds and QUICKBUILD=1.
sed -i 's|^REPO="${GITHUB_REPOSITORY:-btbn/ffmpeg-builds}"$|REPO="${BTBN_IMAGE_REPO:-${GITHUB_REPOSITORY:-btbn/ffmpeg-builds}}"|' util/vars.sh
grep -q 'BTBN_IMAGE_REPO' util/vars.sh || { echo "prepare.sh: util/vars.sh REPO line changed upstream; update the sed" >&2; exit 1; }

# NO_LOCAL_CACHE=1 skips makeimage.sh's buildx cache export (type=local, mode=max: several GB under .cache), which
# only pays off for repeated local builds and overflows a hosted CI runner's disk.
sed -i "s|^\(\s*\)to_bake '  cache-to |\1[[ -n \"\$NO_LOCAL_CACHE\" ]] \|\| to_bake '  cache-to |" makeimage.sh
[[ "$(grep -c 'NO_LOCAL_CACHE' makeimage.sh)" == 3 ]] || { echo "prepare.sh: makeimage.sh cache-to lines changed upstream; update the sed" >&2; exit 1; }

# download.sh globs scripts.d/*/*.sh without nullglob; a flavour that keeps no stage directory (audio-lgpl) would
# otherwise feed the literal pattern to the container as a stage.
sed -i 's|^for STAGE in scripts.d/\*.sh scripts.d/\*/\*.sh; do$|shopt -s nullglob\nfor STAGE in scripts.d/*.sh scripts.d/*/*.sh; do\nshopt -u nullglob|' download.sh
grep -q 'shopt -s nullglob' download.sh || { echo "prepare.sh: download.sh stage loop changed upstream; update the sed" >&2; exit 1; }

cp "$HERE"/addins/*.sh addins/
echo "$FLAVOR" > FLAVOR
git rev-parse HEAD > BTBN_COMMIT
echo "== ready: $WORK (flavour $FLAVOR, BtbN $(cat BTBN_COMMIT))"
